--1) WAQ TO FIND THE NUMBER OF CALLS BETWEEN TWO PERSONS

CREATE TABLE CALLS (FROM_ID INT, TO_ID INT, DURATION INT);

INSERT INTO CALLS VALUES (1,2,59), (2,1,11), (1,3,20), (3,4,100), (3,4,200), (3,4,200), (4,3,499);

SELECT LEAST(FROM_ID, TO_ID) P1,
       GREATEST(FROM_ID, TO_ID) P2,
       COUNT(*) CALL_COUNT,
       SUM(DURATION) DURATION
FROM CALLS
GROUP BY LEAST(FROM_ID, TO_ID),
         GREATEST(FROM_ID, TO_ID);

-- ANOTHER WAY --------------------------------

SELECT MAX(CASE WHEN FROM_ID < TO_ID THEN FROM_ID ELSE TO_ID END) P1,
       MAX(CASE WHEN FROM_ID > TO_ID THEN FROM_ID ELSE TO_ID END) P2,
       COUNT(*) CALL_COUNT,
       SUM(DURATION) DURATION
FROM CALLS
GROUP BY CASE WHEN FROM_ID < TO_ID THEN FROM_ID ELSE TO_ID END,
         CASE WHEN FROM_ID > TO_ID THEN FROM_ID ELSE TO_ID END;

----------------------------------------------------------------------------------------------------------------------------------------------------------------
--2) WAQ TO FIND THE CONSECUTIVE SEATS WHERE 1 IS AVAILABLE AND 0 IS BOOKED

CREATE TABLE CINEMA (
    SEAT_ID INT PRIMARY KEY,
    FREE INT
);

DELETE FROM CINEMA;

INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (1, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (2, 0);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (3, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (4, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (5, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (6, 0);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (7, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (8, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (9, 0);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (10, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (11, 0);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (12, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (13, 0);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (14, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (15, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (16, 0);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (17, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (18, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (19, 1);
INSERT INTO CINEMA (SEAT_ID, FREE) VALUES (20, 1);

-- METHOD 1

WITH CTE AS (
    SELECT *,
           ROW_NUMBER() OVER (ORDER BY SEAT_ID) RN,            -- GENERATING ROW NUMBER
           SEAT_ID - ROW_NUMBER() OVER (ORDER BY SEAT_ID) GRP  -- CREATING GROUP BY SUBTRACTING SEAT_ID FROM ROW NUMBER
    FROM CINEMA
    WHERE FREE = 1   -- FILTERING FOR ONLY AVAILABLE ONES
),
B AS (
    SELECT SEAT_ID, GRP, COUNT(*) OVER (PARTITION BY GRP) CT 
    FROM CTE  -- COUNTING HOW MANY SEATS ARE THERE IN GROUP
)
SELECT SEAT_ID 
FROM B 
WHERE CT > 1;

-- METHOD 2 USING SELF JOIN

WITH CTE AS (
    SELECT C1.SEAT_ID S1, C2.SEAT_ID S2 
    FROM CINEMA C1 
    JOIN CINEMA C2 
    ON C1.SEAT_ID + 1 = C2.SEAT_ID 
    WHERE C1.FREE = 1 AND C2.FREE = 1  -- JOINING ON SEAT_ID CONSECUTIVE SEAT_ID BY FILTERING ONLY FREE SEATS
)
SELECT S1 SEAT_ID 
FROM CTE 
UNION 
SELECT S2 SEAT_ID 
FROM CTE;

-- METHOD 3

WITH CTE AS (
    SELECT *,
           LAG(FREE) OVER (ORDER BY SEAT_ID) PREV,
           LEAD(FREE) OVER (ORDER BY SEAT_ID) NEXT 
    FROM CINEMA
)
SELECT SEAT_ID 
FROM CTE 
WHERE FREE = 1 AND (PREV = 1 OR NEXT = 1);
------------------------------------------------------------------------------------------------------------------------------------------------------------
---------3)  FIND DEPARTMENT WISE MINIMUM SALARY EMPLOYEE NAME AND MAXIMUM SALARY EMPLOYEE NAME

CREATE TABLE EMPS_TBL (
    EMP_NAME VARCHAR(50), 
    DEPT_ID INT, 
    SALARY INT
);

INSERT INTO EMPS_TBL VALUES 
    ('SIVA', 1, 30000), 
    ('RAVI', 2, 40000), 
    ('PRASAD', 1, 50000), 
    ('SAI', 2, 20000), 
    ('ANNA', 2, 10000);

SELECT * FROM EMPS_TBL;

SELECT DEPT_ID,
       MAX(CASE WHEN RK = 1 THEN EMP_NAME END) HIGH_E,
       MAX(CASE WHEN RKK = 1 THEN EMP_NAME END) LOW_E
FROM (
    SELECT DEPT_ID, 
           EMP_NAME, 
           SALARY,
           RANK() OVER (PARTITION BY DEPT_ID ORDER BY SALARY DESC) RK,
           RANK() OVER (PARTITION BY DEPT_ID ORDER BY SALARY) RKK
    FROM EMPS_TBL
) AB
GROUP BY DEPT_ID;
-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- WAQ TO DERIVE THE STATUS OF THE PERFORMANCE OF THE EMPLOYEE. IF PERSON IS HAVING HIGHEST SALARY IN THEIR DEPT THEN PERSON IS TOP PERFORMER
--ELSE IF DIFF BETWEEN PERSON SALARY AND MAX SALRY OF DE[T IS < 10% THEN AVG PERFORMER ELSE WORST PERFORMER
--CREATE TABLE AND INSERT DATA INTO EMPLOYEES

CREATE TABLE EMPLOYEES (
    EMPLOYEEID INT PRIMARY KEY,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10, 2)
);

INSERT INTO EMPLOYEES (EMPLOYEEID, NAME, DEPARTMENT, SALARY) VALUES 
    (1, 'ALICE', 'SALES', 5000.00),
    (2, 'BOB', 'SALES', 6000.00),
    (3, 'CHARLIE', 'SALES', 5500.00),
    (4, 'DAVID', 'MARKETING', 6500.00),
    (5, 'EVA', 'MARKETING', 7000.00),
    (6, 'FRANK', 'MARKETING', 6200.00),
    (7, 'GRACE', 'IT', 7500.00),
    (8, 'HANK', 'IT', 7200.00);

-- CTE TO CLASSIFY EMPLOYEES BASED ON SALARY AND RANK

WITH CTE AS (
    SELECT *, 
           DENSE_RANK() OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) RK,
           MAX(SALARY) OVER (PARTITION BY DEPARTMENT) MAX_SAL  -- HERE I AM CALCULATING MAX SALARY DEPT WISE USING WINDOW FUNCTION
    FROM EMPLOYEES
)

SELECT EMPLOYEEID, 
       NAME, 
       DEPARTMENT, 
       SALARY,
       CASE 
           WHEN RK = 1 THEN 'TOP PERFORMER'
           WHEN (MAX_SAL - SALARY) < SALARY * 0.1 THEN 'AVG' -- HERE CHECKING IF THE DIFF BW MAX SAL AND SAL IS LESS THAN 10 % OF SALARY OR NOT
           ELSE 'WORST' 
       END EMP_RANK
FROM CTE;

--- -------ANOTHER WAY

WITH CTE AS(
              SELECT *,
              DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) RK,
              MAX(SALARY)OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) MAX_SAL
              FROM EMPLOYEES
            )

SELECT *,((MAX_SAL - SALARY)/SALARY)*100,  -- HERE I AM CALCULATING WHAT PERCENTAGE DIFFERENCE OF SALARY COMPARE TO MAX SALARY
CASE WHEN RK = 1 THEN 'TOP '
WHEN ((MAX_SAL - SALARY)/SALARY)*100 < 10 THEN 'AVG'
ELSE 'WORST' END STATUS FROM CTE
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
------WAQ TO GET THE HIGHEST AND LOWEST POPULATED CITY IN EACH STATE

CREATE TABLE city_population (
    state VARCHAR(50),
    city VARCHAR(50),
    population INT
);

-- Insert the data
INSERT INTO city_population (state, city, population) VALUES ('haryana', 'ambala', 100);
INSERT INTO city_population (state, city, population) VALUES ('haryana', 'panipat', 200);
INSERT INTO city_population (state, city, population) VALUES ('haryana', 'gurgaon', 300);
INSERT INTO city_population (state, city, population) VALUES ('punjab', 'amritsar', 150);
INSERT INTO city_population (state, city, population) VALUES ('punjab', 'ludhiana', 400);
INSERT INTO city_population (state, city, population) VALUES ('punjab', 'jalandhar', 250);
INSERT INTO city_population (state, city, population) VALUES ('maharashtra', 'mumbai', 1000);
INSERT INTO city_population (state, city, population) VALUES ('maharashtra', 'pune', 600);
INSERT INTO city_population (state, city, population) VALUES ('maharashtra', 'nagpur', 300);
INSERT INTO city_population (state, city, population) VALUES ('karnataka', 'bangalore', 900);
INSERT INTO city_population (state, city, population) VALUES ('karnataka', 'mysore', 400);
INSERT INTO city_population (state, city, population) VALUES ('karnataka', 'mangalore', 200);


--ONE WAY USING RANK
WITH CTE AS (
    SELECT *,
           RANK() OVER (PARTITION BY STATE ORDER BY POPULATION) AS RK,
           RANK() OVER (PARTITION BY STATE ORDER BY POPULATION DESC) AS RKK
    FROM CITY_POPULATION
)
SELECT STATE,
       MAX(CASE WHEN RK = 1 THEN CITY END) AS LESS_POPULATED,
       MAX(CASE WHEN RKK = 1 THEN CITY END) AS HIGH_POPULATED
FROM CTE
GROUP BY STATE;

--ANOTHER WAY USING FIRST_VALUE AND LAST_VALUE

SELECT STATE,
       MAX(LESS_PP) AS LESS_POPULATED,
       MAX(HIGH_POP) AS HIGH_POPULATED
FROM (
    SELECT STATE,
           FIRST_VALUE(CITY) OVER (PARTITION BY STATE ORDER BY POPULATION) AS LESS_PP,
           LAST_VALUE(CITY) OVER (PARTITION BY STATE ORDER BY POPULATION
                                  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS HIGH_POP
    FROM CITY_POPULATION
) AB
GROUP BY STATE;

--ANOTHER WAY USING MAX WINDOW FUNCTION

WITH CTE AS(
              SELECT *,
              MAX(POPULATION) OVER(PARTITION BY STATE) MAX_POP,
              MIN(POPULATION) OVER(PARTITION BY STATE) MIN_POP 
              FROM CITY_POPULATION
          )

SELECT STATE,
MAX(CASE WHEN POPULATION = MIN_POP THEN CITY END) MIN_POPULATION,
MAX(CASE WHEN POPULATION = MAX_POP THEN CITY END) MAX_POPULATION
FROM CTE GROUP BY STATE

----------------------------------------------------------------------------------------------------------------------------------------------------
--WAQ TO GET THE PRODUCT NAME WHICH CONTRIBUTE 80% OF THE TOTAL SALES
CREATE TABLE Products (

    ProductID INT PRIMARY KEY,

    Name VARCHAR(50),

    Sales DECIMAL(10, 2)

);



-- Insert data into the table

INSERT INTO Products (ProductID, Name, Sales) VALUES

(1, 'Laptop', 8000.00),

(2, 'Smartphone', 7000.00),

(3, 'Tablet', 1500.00),

(4, 'Headphones', 800.00),

(5, 'Smartwatch', 700.00),

(6, 'Monitor', 500.00),

(7, 'Keyboard', 300.00),

(8, 'Mouse', 200.00),

(9, 'Charger', 100.00),

(10, 'USB Cable', 100.00);

----SOLUTION
WITH CTE AS (
    SELECT *, 
           SUM(SALES) OVER() TOT_SALES,
           (SALES / SUM(SALES) OVER()) * 100 PERC
    FROM PRODUCTS
),
B AS (
    SELECT *, 
           SUM(PERC) OVER(ORDER BY PRODUCTID) RUNNING
    FROM CTE
)
SELECT PRODUCTID, NAME 
FROM B 
WHERE RUNNING < 80;

-----------------------------------------------------------------------------------------------------------------------
--WAQ TO FIND THE INCENTIVES OF THE DTIVERS BASED ON THE BELOW CONDITIONS
-- IF DELIVERY PASS %> 80 OR AVG RATING >4.7 THEN BEST
-- IF DELIVERY PASSS %>60 OR AVG RATING >4.5 THEN GOOD ELSE BAD

-- IF PERFORMANCE IS BEST THEN INCENTIVE IS 500 FOR GOOD 200 FOR BAD 0

CREATE TABLE RIDES (

    DRIVERID INT,
    NAME VARCHAR(50),
    RIDEID INT PRIMARY KEY,
    STARTTIME DATETIME,
    ENDTIME DATETIME,
    ETA INT,
RATING DECIMAL(2, 1)

);

INSERT INTO RIDES (DRIVERID, NAME, RIDEID, STARTTIME, ENDTIME, ETA, RATING) VALUES
(1, 'JOHN', 101, '2024-09-01 08:00:00', '2024-09-01 08:30:00', 35, 4.8),
(2, 'EMILY', 102, '2024-09-01 09:00:00', '2024-09-01 09:45:00', 50, 4.7),
(3, 'DAVID', 103, '2024-09-01 10:00:00', '2024-09-01 10:50:00', 55, 4.5),
(4, 'JESSICA', 104, '2024-09-01 11:00:00', '2024-09-01 11:30:00', 40, 4.9),
(5, 'MICHAEL', 105, '2024-09-01 12:00:00', '2024-09-01 12:25:00', 15, 4.6),
(1, 'JOHN', 106, '2024-09-02 08:15:00', '2024-09-02 08:45:00', 40, 4.8),
(2, 'EMILY', 107, '2024-09-02 09:30:00', '2024-09-02 10:15:00', 50, 4.7),
(3, 'DAVID', 108, '2024-09-02 10:30:00', '2024-09-02 11:20:00', 52, 4.6),
(4, 'JESSICA', 109, '2024-09-02 11:45:00', '2024-09-02 12:10:00', 15, 5.0),
(5, 'MICHAEL', 110, '2024-09-02 12:30:00', '2024-09-02 12:55:00', 18, 4.5),
(1, 'JOHN', 111, '2024-09-03 07:50:00', '2024-09-03 08:20:00', 35, 4.9),
(2, 'EMILY', 112, '2024-09-03 09:10:00', '2024-09-03 09:50:00', 45, 4.8),
(3, 'DAVID', 113, '2024-09-03 10:40:00', '2024-09-03 11:30:00', 45, 4.4),
(4, 'JESSICA', 114, '2024-09-03 11:20:00', '2024-09-03 11:50:00', 20, 4.9),
(5, 'MICHAEL', 115, '2024-09-03 12:10:00', '2024-09-03 12:40:00', 15, 4.7),
(1, 'JOHN', 116, '2024-09-04 08:05:00', '2024-09-04 08:35:00', 28, 4.6),
(2, 'EMILY', 117, '2024-09-04 09:25:00', '2024-09-04 10:05:00', 40, 4.8),
(3, 'DAVID', 118, '2024-09-04 10:50:00', '2024-09-04 11:40:00', 48, 4.6),
(4, 'JESSICA', 119, '2024-09-04 11:30:00', '2024-09-04 11:55:00', 22, 5.0),
(5, 'MICHAEL', 120, '2024-09-04 12:20:00', '2024-09-04 12:45:00', 18, 4.1);

--SOLUTION
WITH CTE AS (
    SELECT DRIVERID, NAME,
           SUM(CASE WHEN DATEDIFF(MI, STARTTIME, ENDTIME) <= ETA THEN 1 ELSE 0 END) AS SUCCESSFULRIDES,
           AVG(RATING) AS AVG_RATING
    FROM RIDES
    GROUP BY DRIVERID, NAME
),

B AS (
    SELECT DRIVERID, COUNT(DRIVERID) AS TOTALRIDES
    FROM RIDES
    GROUP BY DRIVERID
)

SELECT A.DRIVERID, A.NAME,
       CASE 
           WHEN A.SUCCESSFULRIDES * 100.00 / B.TOTALRIDES > 80 OR A.AVG_RATING > 4.7 THEN 500
           WHEN A.SUCCESSFULRIDES * 100.00 / B.TOTALRIDES > 60 OR A.AVG_RATING > 4.5 THEN 200
           ELSE 0
       END AS INCENTIVE
FROM CTE A
JOIN B ON A.DRIVERID = B.DRIVERID;
------------------------------------------------------------------------------------------------------------------------------------------------
--WAQ TO GET THE MISSING WEEKS
CREATE TABLE SLS_TBL (PID INT, SLS_DT DATE, SLS_AMT INT);

-- Insert data into the table
INSERT INTO SLS_TBL (PID, SLS_DT, SLS_AMT)
VALUES 
    (201, '2024-07-11', 140), 
    (201, '2024-07-18', 160), 
    (201, '2024-07-25', 150), 
    (201, '2024-08-01', 180), 
    (201, '2024-08-15', 170), 
    (201, '2024-08-29', 130);
---SOLUTION
WITH CTE AS (
    SELECT *,
           LEAD(SLS_DT) OVER (ORDER BY SLS_DT) AS NXTDAY,
           DATEDIFF(DAY, SLS_DT, LEAD(SLS_DT) OVER (ORDER BY SLS_DT)) AS DIFF
    FROM SLS_TBL
)
SELECT CASE WHEN DIFF > 7 THEN DATEADD(DAY, 7, SLS_DT) END AS MISSING_WK
FROM CTE
WHERE DIFF > 7;

